#!/usr/bin/env bash
## Re sync configs and disable cache modules.
##
## Usage: fin local/cim

set -eo pipefail

. "./.docksal/commands/local/helpers.sh"

echo_color "Installing dependencies..."
time fin composer install

echo_color green "Importing local changes."
time fin blt du -n

echo_color green "Changing permissions of files folder."
time fin exec chmod -R 755 /var/www/docroot/sites/default/files

echo_color green "Disable cache module."
time fin drush pm:uninstall advagg -y

echo_color green "Clear cache."
time fin drush cr

echo_color green "Create one time login link."
time fin drush uli
