#!/usr/bin/env bash
## Sync database, files, adjust permissions and local environment.
##
## envs: [dev|test|prod]
## default: dev
## Usage: fin local/sync [dev|test|prod]

set -eo pipefail

site_alias=""
env=${1:-dev}

if [[ -z "${site_alias}" ]]; then
  echo "Error: site alias not set."
  exit 1
fi

if ! [[ "${env}" =~ ^(test|dev|prod)$ ]]; then
  echo "Usage: fin local/sync [dev|test|prod]"
  exit 1
fi

echo "Installing dependencies..."
time fin composer install

echo "Syncing database from ${env}..."
time fin drush sql-sync --extra-dump="--no-tablespaces" --structure-tables-list="past_event_data,key_value_expire,cache,cache_filter,cache_menu,cache_page,history,sessions,watchdog,redirect_404" @${site_alias}.${env} @self -y

# Clear cache.
time fin drush cr

# Run updates.
fin local/cim
