#!/usr/bin/env bash
## Create one user per role.
##
## Usage: fin local/users

. "./.docksal/commands/local/helpers.sh"

function create_user() {
  role=$1
  user="${role}.imagex"
  email="${user}@imagexmedia.com"
  password=$(openssl rand -base64 12)

  # Avoid error if user already exists.
  user_exists=$(fin drush uli --mail="${email}")
  user_exists_status=${?}
  if [[ "${user_exists_status}" == 1 ]]; then
    echo_color green "Creating user ${user} ..."
    fin drush ucrt "${user}" --mail="${email}" --password="${password}"
  fi

  if [[ "${role}" != "authenticated" ]]; then
    echo_color green "Adding role ${role} to user ${user}"
    fin drush user-add-role "${role}" "${user}"
  fi

  echo_color green "Generating one time login..."
  if [[ "${user_exists_status}" == 1 ]]; then
    fin drush uli --mail="${email}"
  else
    echo ${user_exists}
  fi

}

roles=$(fin drush role:list --fields=rid)
roles=${roles// /}
for role in ${roles}; do
  role=$(echo ${role%:*} | sed '/^[[:space:]]*$/d')
  # Ignore this roles because they need to be set manually via cms.
  if [[ "${role}" == "anonymous" ]]; then
    continue
  fi
  if [[ ! -z "${role}" ]]; then
    echo_color green "Creating user for role ${role}"
    time create_user "${role}"
  fi
done

