#!/usr/bin/env bash
## Run the theme watch command outside the container.
##
## Usage: fin local/theme/watch

set -eo pipefail

. "./.docksal/commands/local/helpers.sh"

theme_folder=""

if [[ -z "${1}" ]]; then
  echo_color red "Error: theme path is required"
  exit 1
fi

theme_pre_run ${theme_folder} ${2-false}

echo_color green "Building theme..."
npm run --prefix ${theme_folder} watch

